### ISSUE TITLE
Medium level

### ISSUE THREAD

**Issue by BiKit** [antonio081014/ABatteryView#6]
How to add a medium level in yellow from 20 to 50%

**Comment by BiKit** [comment]
I made some changes in my own, I would like to ask you if I did it right or not. 
I add: `        <attr name="mediumLevel" format="integer"/>` in attrs_baterry_view 

`                custom:warningLevel="20"
                custom:mediumLevel="50"` in the XML file and
change in BatteryView.java
`if(mlevelColors)
        fillColor =(mLevel <= warningLevel)?Color.RED:Color.GREEN;` 
to 
`switch (mlevelColors) {
            case mLevel <= warningLevel :
                fillColor = Color.RED;
                break;
            case mLevel > warningLevel && mLevel<= mediumLevel:
                fillColor = Color.YELLOW;
                break;
            default:
                fillColor=Color.GREEN;
                break;
        }`
I also add `private int mediumLevel;` and `mediumLevel= a.getInteger(R.styleable.BatteryView_mediumLevel, 50);`
for which i got 
> error: incompatible types: boolean cannot be converted to int

so I change the switch case with
`if (mLevel <= warningLevel) fillColor = Color.RED;
        else if (mLevel > warningLevel && mLevel <= mediumLevel) fillColor = Color.YELLOW;
        else fillColor = Color.GREEN;`

**Comment by antonio081014** [comment]
I think you got it right.
